name: Generate Clash rule sets
on:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release
      - name: Generate AWS Cloudfront CIDR
        uses: sergeysova/jq-action@v2
        with: 
          cmd: |
            curl -fsSL https://ip-ranges.amazonaws.com/ip-ranges.json \
            | jq -r '.prefixes[] | select(.service == "CLOUDFRONT") | .ip_prefix' \
            | sort -n -t. \
            > aws-cloudfront-cidr.txt
      - name: Generate Cloudflare CIDR
        run: |
          curl -fsSL https://www.cloudflare.com/ips-v4 \
          | sort -n -t. \
          > cloudflare-cidr.txt
      - name: Generate Fastly CIDR
        uses: sergeysova/jq-action@v2
        with: 
          cmd: |
            curl -fsSL https://api.fastly.com/public-ip-list \
            | jq -r '.addresses[]' \
            | sort -n -t. \
            > fastly-cidr.txt
      - name: Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated at `date -u +%Y-%m-%dT%H:%M:%S%Z`"
          git tag -a latest -m "Updated at `date -u +%Y-%m-%dT%H:%M:%S%Z`"
          git push --follow-tags
